# Generated by Django 5.0.2 on 2024-03-18 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tracks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_name', models.CharField(max_length=256)),
                ('track_uuid', models.CharField(max_length=36)),
                ('track_original_path', models.CharField(max_length=256)),
                ('track_date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_name', models.CharField(max_length=256)),
                ('tracks', models.ManyToManyField(to='api.tracks')),
            ],
        ),
    ]
