# Generated by Django 5.0.2 on 2024-03-30 19:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_title', models.CharField(max_length=256)),
                ('track_artist', models.CharField(max_length=256)),
                ('track_album', models.CharField(max_length=256)),
                ('track_duration', models.FloatField()),
                ('track_minutes', models.IntegerField()),
                ('track_seconds', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='playlist',
            name='playlist_created_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 3, 30, 19, 36, 18, 416499, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playlist',
            name='playlist_type',
            field=models.CharField(choices=[('USER', 'user'), ('SYSTEM', 'system')], default='USER', max_length=12),
        ),
    ]
