# Generated by Django 5.0.2 on 2024-03-30 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_trackinfo_playlist_playlist_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='playlist_uuid',
            field=models.CharField(default='183dbc00-9c09-422e-b5b8-19339410d1c3', max_length=36),
        ),
    ]
