# Generated by Django 5.0.14 on 2026-03-20 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_playlist_playlist_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='playlist_uuid',
            field=models.CharField(default='b6bae490-6145-4b5e-83e3-92131933d435', max_length=36),
        ),
    ]
