# Generated by Django 5.0.14 on 2026-03-20 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_playlist_playlist_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='playlist_uuid',
            field=models.CharField(default='277b47de-1612-4c9f-a412-1df924c6a5f2', max_length=36),
        ),
    ]
