# Generated by Django 5.0.14 on 2026-03-20 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_playlist_playlist_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='playlist_uuid',
            field=models.CharField(default='bdc9cbc0-f5df-427d-bf90-affe1c3914db', max_length=36),
        ),
    ]
