# Generated by Django 5.0.14 on 2026-03-20 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_playlist_playlist_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='playlist_uuid',
            field=models.CharField(default='fce26b4c-4574-4e8b-886b-411aa547365c', max_length=36),
        ),
    ]
