# Generated by Django 5.0.14 on 2026-03-20 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_playlist_playlist_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='playlist_uuid',
            field=models.CharField(default='1d83825d-c654-4ec6-a479-eb90eee3275b', max_length=36),
        ),
    ]
