# Generated by Django 5.0.14 on 2026-03-20 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_playlist_playlist_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='playlist_uuid',
            field=models.CharField(default='270fd5bb-72db-483d-8afa-2d675b52786c', max_length=36),
        ),
    ]
