# Generated by Django 5.0.14 on 2026-03-20 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_playlist_playlist_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='playlist_uuid',
            field=models.CharField(default='58d8b4eb-6eab-449a-976d-a77de1bdd411', max_length=36),
        ),
    ]
